#!/bin/bash

HOME_ENV="-e HOME=/home"
UID_FLAG="-u $UID"

# On OSX, you're using a VM that runs as user 1000 and root in the container. Bad vboxsf things happen.
case "$OSTYPE" in
    darwin*)
        $HOME_ENV = "-e HOME=/root"
        $UID_FLAG = ""
    ;;
esac

docker-compose run \
    --rm \
    $HOME_ENV \
    $UID_FLAG \
    -e TERM=$TERM \
    --entrypoint="$1" \
    webapp "${@:2}"
